# permissions for end users to edit gommaapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: gommaapp-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: gommaapp-editor-role
rules:
- apiGroups:
  - gomma.devlikebear.app
  resources:
  - gommaapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gomma.devlikebear.app
  resources:
  - gommaapps/status
  verbs:
  - get
