---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - gomma.devlikebear.app
  resources:
  - gommaapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gomma.devlikebear.app
  resources:
  - gommaapps/finalizers
  verbs:
  - update
- apiGroups:
  - gomma.devlikebear.app
  resources:
  - gommaapps/status
  verbs:
  - get
  - patch
  - update
