apiVersion: gomma.devlikebear.app/v1
kind: GommaApp
metadata:
  labels:
    app.kubernetes.io/name: gommaapp
    app.kubernetes.io/instance: gommaapp
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: gomma
spec:
  # TODO(user): Add fields here
